osx_image: xcode7.3

language: objective-c
cache: cocoapods
podfile: Podfile

before_install:
    - gem install xcpretty -N

script:
    - xcodebuild -workspace glucosio.xcworkspace -scheme glucosio -sdk iphonesimulator test | xcpretty -c